# Generated by Django 4.1.7 on 2023-03-02 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slugi')),
                ('slider', models.ImageField(upload_to='article/sliders/', verbose_name='Rasmi')),
                ('short_description', models.CharField(max_length=250, verbose_name='Qisqa tevsif')),
                ('description', models.TextField(verbose_name='Maqola matni')),
                ('type', models.CharField(choices=[('New', 'Yangi'), ('Draft', 'Qoralama'), ('Popular', 'Mashhur'), ('Actual', 'Dolzarb')], default='New', max_length=20, verbose_name='Maqola turi')),
                ('time_to_read', models.PositiveIntegerField(default=1, help_text='Minutlarda kiriting', verbose_name='O`qish uchun vaqt')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Ko`rishlar soni')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.SH.')),
                ('avatar', models.ImageField(upload_to='author/avatar/', verbose_name='Rasmi')),
                ('bio', models.TextField(verbose_name='Muallif haqida ma`lumot')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('avatar', models.ImageField(upload_to='category/avatars/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('email', models.EmailField(max_length=100, verbose_name='Elektron pochta')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzusi')),
                ('text', models.TextField(verbose_name='Xabar matni')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kasb',
                'verbose_name_plural': 'Kasblar',
            },
        ),
        migrations.CreateModel(
            name='Social_network_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('logo', models.ImageField(upload_to='social_network/logo/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq turi',
                'verbose_name_plural': 'Ijtimoiy tarmoq turlari',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH.')),
                ('email', models.EmailField(max_length=100, verbose_name='Elektron poschta')),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachilar',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Teg',
                'verbose_name_plural': 'Teglar',
            },
        ),
        migrations.CreateModel(
            name='Social_network_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('nickname', models.CharField(max_length=150, verbose_name='Foydalanuvchi nomi')),
                ('profile_link', models.CharField(max_length=200, verbose_name='Profil uchun link')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Muallif')),
                ('social_network_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.social_network_type')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq sahifasi',
                'verbose_name_plural': 'Ijtimoiy tarmoq sahifalari',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('text', models.CharField(max_length=250, verbose_name='Izoh matni')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='Maqola')),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subscriber', verbose_name='Muallifi')),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='professions',
            field=models.ManyToManyField(to='blog.profession'),
        ),
        migrations.AddField(
            model_name='author',
            name='subscribers',
            field=models.ManyToManyField(to='blog.subscriber'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Karegoriya'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
